#!/data/data/com.termux/files/usr/bin/bash

DATA_DIRECTORY="data"

npm run build
if [ ! -d "./$DATA_DIRECTORY" ]; then
  mv "../$DATA_DIRECTORY" "./$DATA_DIRECTORY"
  echo "./data => ../data"
fi

rm -rf ./static/
git add .
git commit -m "[build]: update react build"
git push origin master
mkdir ./static
cp ./public/* ./static/ -r
cp ./dist/* ./static/ -r

mv "../$DATA_DIRECTORY" "./$DATA_DIRECTORY"

echo "done ..."